### ISSUE TITLE
How to resend the confirmation code?

### ISSUE THREAD

**Issue by Ricardo1980** [mobilequickie/amplify-passwordless-sms-auth#11]
Hello,

After calling:
AWSMobileClient.default().signUp and  AWSMobileClient.default().signIn
we have to call AWSMobileClient.default().confirmSignIn(challengeResponse: code) with the correct code in order to complete the sign in.

What about if we don't receive the message? How can we retry that?

If I call 
AWSMobileClient.default().resendSignUpCode(username: "-my phone number-",
I receive:

```
▿ AWSMobileClientError
  ▿ notAuthorized : 1 element
    - message : "Cannot resend codes. Auto verification not turned on."
```

Any recommendation?

Thanks a lot.

**Comment by tomaszdudek7** [comment]
@Ricardo1980 did you solve your issue?

**Comment by Ricardo1980** [comment]
Not at the moment.
But I will have to do it in the future.

**Comment by dcchristopher** [comment]
@Ricardo1980 The flow you describe above is more akin to the built-in verification (via email or SMS). With a custom authentication flow, you don't use confirmSignIn or resendSignUpCode. You simply use signIn(mobileNumber) (notice, only one parameter) which triggers the custom auth flow. That ought to trigger the sending of the SMS code. Then you use sendCustomChallengeAnswer with the SMS code to confirm the sign-up/-in. I hope this helps!

**Comment by Ricardo1980** [comment]
@tomaszdudek7
Check this:
https://github.com/aws-amplify/aws-sdk-ios/issues/2261
Basically, call AWSMobileClient.default().signOut() and then start the signUp/signIn sequence again.
