### ISSUE TITLE
How to implement using android amplify library

### ISSUE THREAD

**Issue by ypawar159** [mobilequickie/amplify-passwordless-sms-auth#23]
I have tried this code using the web version, after tinkering with the sns settings got it working fine.
To implement the client in android app I changed default config to `CUSTOM_AUTH`, that passed first singin call. But now stuck at second stage where the response to the challenge needs to be submitted.
What is the substitute for following js api call in android amplify library?.
`Auth.sendCustomChallengeAnswer(user, OTP);`
I couldn't find any equivalent. `confirmSignIn` is for mfa so not useful here.
Is there any quick alternative to have that specific api call? As I am using Retrofit lib, any guide to use it to achieve this?

**Comment by NewVengeance** [comment]
did you find solution?

**Comment by ypawar159** [comment]
I used escape hatch.
```kotlin
fun confirmSignIn(challgeneCode: String) {
        val res: MutableMap<String, String> =
            HashMap()
        res[CognitoServiceConstants.CHLG_RESP_ANSWER] = challgeneCode
        val mobileClient =
            Amplify.Auth.getPlugin("awsCognitoAuthPlugin").escapeHatch as AWSMobileClient
        mobileClient.confirmSignIn(res, object : Callback<SignInResult?> {
            override fun onError(e: Exception?) {
                Log.e(LogTag, "Confirm Custom auth Sign-in error", e)
            }
            override fun onResult(result: SignInResult?) {
                Log.d(LogTag, "Result signin state = ${result?.signInState}")
                if (result?.signInState == SignInState.DONE) {
                    GlobalScope.launch(Dispatchers.Main) {
                        Toast.makeText(applicationContext, "Auth success", Toast.LENGTH_SHORT)
                            .show()
                        // Other app code
                    }
                }
            }
        })
    }
```

And btw I have moved away from the cognito. It creates more problem than it solves for other business logic implementation.

**Comment by NewVengeance** [comment]
Thanks

**Comment by NewVengeance** [comment]
I need some more help can we talk in facebook?
